---
- hosts: all
  become: yes

  tasks:

    - name: stop current running container
      command: docker stop test-container
      ignore_errors: yes

    - name: remove stopped docker container
      command: docker rm test-container
      ignore_errors: yes

    - name: remove current docker image
      command: docker rmi meltonmajor/test-image:latest
      ignore_errors: yes

    - name: pull docker image from dockerhub
      command: docker pull meltonmajor/test-image:latest

    - name: creating docker container using test-image
      command: docker run -d --name test-container -p 8080:8080 meltonmajor/test-image:latest
